import { Product, Store, Category, User } from "./types";

// Mock Products Data
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    image: "/produtos/oculos-1.png",
    hoverImage: "/produtos/oculos-1-hover.png",
    model: "Aviador Classic",
    brand: "Ray-Ban",
    price: 450.0,
    promotionalPrice: 380.0,
    category: "oculos-sol",
    description:
      "Óculos aviador clássico com lentes polarizadas e proteção UV400. Design atemporal que combina com qualquer estilo.",
    specifications: {
      "Material da Armação": "Metal",
      "Tipo de Lente": "Polarizada",
      "Proteção UV": "UV400",
      "Cor da Armação": "Dourado",
      "Cor da Lente": "Verde G-15",
    },
    inStock: true,
    stockQuantity: 15,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: 2,
    image: "/produtos/oculos-2.png",
    hoverImage: "/produtos/oculos-2-hover.png",
    model: "Wayfarer Original",
    brand: "Ray-Ban",
    price: 420.0,
    category: "oculos-sol",
    description:
      "O icônico Wayfarer com design original dos anos 50. Perfeito para quem busca estilo e qualidade.",
    specifications: {
      "Material da Armação": "Acetato",
      "Tipo de Lente": "Standard",
      "Proteção UV": "UV400",
      "Cor da Armação": "Preto",
      "Cor da Lente": "Verde Clássico",
    },
    inStock: true,
    stockQuantity: 8,
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-18T16:45:00Z",
  },
  {
    id: 3,
    image: "/produtos/oculos-3.png",
    hoverImage: "/produtos/oculos-3-hover.png",
    model: "Round Metal",
    brand: "Ray-Ban",
    price: 380.0,
    promotionalPrice: 320.0,
    category: "oculos-sol",
    description:
      "Óculos redondo em metal com estilo vintage. Ideal para rostos angulares e personalidade marcante.",
    specifications: {
      "Material da Armação": "Metal",
      "Tipo de Lente": "Standard",
      "Proteção UV": "UV400",
      "Cor da Armação": "Dourado",
      "Cor da Lente": "Azul Degradê",
    },
    inStock: true,
    stockQuantity: 12,
    createdAt: "2024-01-12T11:30:00Z",
    updatedAt: "2024-01-22T09:15:00Z",
  },
  {
    id: 4,
    image: "/produtos/oculos-4.png",
    hoverImage: "/produtos/oculos-4-hover.png",
    model: "Executive Pro",
    brand: "Oakley",
    price: 520.0,
    category: "oculos-grau",
    description:
      "Armação executiva em acetato premium. Design sofisticado para o ambiente profissional.",
    specifications: {
      "Material da Armação": "Acetato Premium",
      Tipo: "Grau",
      "Cor da Armação": "Preto Fosco",
      Formato: "Retangular",
      Tamanho: "54-16-140",
    },
    inStock: true,
    stockQuantity: 6,
    createdAt: "2024-01-08T14:20:00Z",
    updatedAt: "2024-01-25T11:00:00Z",
  },
  {
    id: 5,
    image: "/produtos/oculos-5.png",
    hoverImage: "/produtos/oculos-5-hover.png",
    model: "Sport Vision",
    brand: "Oakley",
    price: 680.0,
    promotionalPrice: 580.0,
    category: "oculos-esporte",
    description:
      "Óculos esportivo com tecnologia anti-embaçante e lentes intercambiáveis. Perfeito para atividades ao ar livre.",
    specifications: {
      "Material da Armação": "O-Matter",
      "Tipo de Lente": "Prizm",
      "Proteção UV": "UV400",
      "Cor da Armação": "Preto Polido",
      Tecnologia: "Anti-fog",
    },
    inStock: false,
    stockQuantity: 0,
    createdAt: "2024-01-05T08:45:00Z",
    updatedAt: "2024-01-28T13:20:00Z",
  },
];

// Mock Stores Data
export const MOCK_STORES: Store[] = [
  {
    id: 1,
    name: "Ótica Popular Centro",
    address: "Rua Grande, 1234",
    neighborhood: "Centro",
    city: "Parnaíba",
    state: "PI",
    zipCode: "64200-001",
    phone: "(86) 3321-1234",
    whatsappLink:
      "https://wa.me/5586999391234?text=Olá! Gostaria de saber mais sobre os produtos da Ótica Popular Centro.",
    openingHours: "Seg-Sex: 8h às 18h | Sáb: 8h às 12h",
    coordinates: {
      lat: -2.9048,
      lng: -41.7767,
    },
    isActive: true,
    createdAt: "2023-06-01T10:00:00Z",
    updatedAt: "2024-01-15T14:30:00Z",
  },
  {
    id: 2,
    name: "Ótica Popular São Sebastião",
    address: "Av. São Sebastião, 567",
    neighborhood: "São Sebastião",
    city: "Parnaíba",
    state: "PI",
    zipCode: "64202-020",
    phone: "(86) 3322-5678",
    whatsappLink:
      "https://wa.me/5586999395678?text=Olá! Gostaria de saber mais sobre os produtos da Ótica Popular São Sebastião.",
    openingHours: "Seg-Sex: 8h às 18h | Sáb: 8h às 14h",
    coordinates: {
      lat: -2.8987,
      lng: -41.7823,
    },
    isActive: true,
    createdAt: "2023-08-15T10:00:00Z",
    updatedAt: "2024-01-20T16:45:00Z",
  },
];

// Mock Categories Data
export const MOCK_CATEGORIES: Category[] = [
  {
    id: 1,
    name: "Óculos de Sol",
    slug: "oculos-sol",
    description: "Proteção e estilo para seus olhos",
    image: "/produtos/oculos-1.png",
    isActive: true,
    productCount: 3,
    createdAt: "2023-05-01T10:00:00Z",
    updatedAt: "2024-01-10T12:00:00Z",
  },
  {
    id: 2,
    name: "Óculos de Grau",
    slug: "oculos-grau",
    description: "Visão perfeita com design moderno",
    image: "/produtos/oculos-4.png",
    isActive: true,
    productCount: 1,
    createdAt: "2023-05-01T10:00:00Z",
    updatedAt: "2024-01-10T12:00:00Z",
  },
  {
    id: 3,
    name: "Óculos Esportivos",
    slug: "oculos-esporte",
    description: "Performance e proteção para atletas",
    image: "/produtos/oculos-5.png",
    isActive: true,
    productCount: 1,
    createdAt: "2023-05-01T10:00:00Z",
    updatedAt: "2024-01-10T12:00:00Z",
  },
  {
    id: 4,
    name: "Lentes de Contato",
    slug: "lentes-contato",
    description: "Liberdade e conforto visual",
    image: "/produtos/oculos-2.png",
    isActive: true,
    productCount: 0,
    createdAt: "2023-05-01T10:00:00Z",
    updatedAt: "2024-01-10T12:00:00Z",
  },
];

// Mock Users Data (for testing)
export const MOCK_USERS: User[] = [
  {
    id: "user_1",
    name: "João Silva",
    email: "joao@email.com",
    phone: "(86) 99999-1234",
    avatar: "/avatars/joao.jpg",
    isActive: true,
    createdAt: "2023-12-01T10:00:00Z",
    updatedAt: "2024-01-15T14:30:00Z",
  },
  {
    id: "user_2",
    name: "Maria Santos",
    email: "maria@email.com",
    phone: "(86) 99999-5678",
    isActive: true,
    createdAt: "2023-11-15T09:30:00Z",
    updatedAt: "2024-01-10T16:20:00Z",
  },
];
